# Generated by Django 4.2.30 on 2026-06-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_project_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='logo_props',
            field=models.JSONField(default=dict),
        ),
    ]
